source 'https://rubygems.org'

group :jekyll_plugins do
    gem 'jekyll', '~>3.0'
    gem 'kramdown'
    gem 'rdiscount'
    gem 'jekyll-sitemap'
    gem 'jekyll-redirect-from'
    gem 'jekyll-theme-primer', '~> 0.1.5'
end
